id: CraftEngine.Deps.Types
name: Craft Types
version: "1.0.0"
repo: https://github.com/OffByOneStudios/craft-types

dependencies:
  - CraftEngine.Deps.Util
  
vendor-dependencies:
  win_x64_vc140:
    - mpir
    - mpirxx
  osx_x64_clang:
    - mpir
    - mpirxx
  debian_x64_gcc:
    - mpir
    - mpirxx

platform-dependencies:
  win_x64_vc140: []
  osx_x64_clang: []
  debian_x64_gcc: []
  
platform-flags:
  win_x64_vc140: []
  osx_x64_clang: 
    - "-std=c++1z"
    - "-stdlib=libc++"
    - "-Wc++11-extensions"
  debian_x64_gcc: 
    - "-std=gnu++1z"
    - "-pthread"
    - "-fpermissive"
  

files:
  library:
    - src/**/*.*
  test:
    - test/**/*.*
  entry:
    - entry/**/*.*

