id: Types
namespace: OffByOneStudios
name: Craft Types
version: "1.0.0"
repo: https://github.com/OffByOneStudios/craft-types

dependencies:
  - Util

vendor-dependencies:
  x86_64-pc-windows-msvccoff: []
  x86_64-apple-macosx-macho: []
  x86_64-pc-linux-gnu: []
    
platform-dependencies:
  x86_64-pc-windows-msvccoff: []
  x86_64-apple-macosx-macho: []
  x86_64-pc-linux-gnu:
    - "-dl"

platform-compile-flags:
  x86_64-pc-windows-msvccoff:
    - "/std:c++latest"
    # - "/Zc:__cplusplus" # whoops no string join
  x86_64-apple-macosx-macho:
    - "-std=c++1z"
    - "-stdlib=libc++"
    - "-Wc++11-extensions"
  x86_64-pc-linux-gnu:
    - "-std=gnu++1z"
    - "-pthread"
    - "-fpermissive"

platform-link-flags:
  x86_64-pc-windows-msvccoff:
    - "/ignore:4099"

platform-defines:
  x86_64-pc-windows-msvccoff:
    _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS: yes
  x86_64-apple-macosx-macho: {}
  x86_64-pc-linux-gnu: {}

artifacts:
  library:
    primary: yes
    kind: dll craft-types
    files:
      - src/**/*.*
  test:
    kind: test
    files:
      - test/**/*.*
  entry:
    kind: exe
    files:
      - entry/**/*.*
