#pragma once
#include "syn/syn.h"

CRAFT_TYPE_DECLARE(CRAFT_TYPES_EXPORTED, void*);



CRAFT_TYPE_DECLARE(CRAFT_TYPES_EXPORTED, uint8_t);
CRAFT_TYPE_DECLARE(CRAFT_TYPES_EXPORTED, uint16_t);

CRAFT_TYPE_DECLARE(CRAFT_TYPES_EXPORTED, uint32_t);
CRAFT_TYPE_DECLARE(CRAFT_TYPES_EXPORTED, uint64_t);

CRAFT_TYPE_DECLARE(CRAFT_TYPES_EXPORTED, int8_t);
CRAFT_TYPE_DECLARE(CRAFT_TYPES_EXPORTED, int16_t);

CRAFT_TYPE_DECLARE(CRAFT_TYPES_EXPORTED, int32_t);
CRAFT_TYPE_DECLARE(CRAFT_TYPES_EXPORTED, int64_t);

CRAFT_TYPE_DECLARE(CRAFT_TYPES_EXPORTED, float);
CRAFT_TYPE_DECLARE(CRAFT_TYPES_EXPORTED, double);
