#pragma once
#include "common.h"
#include "core.h"

CRAFT_TYPE_DECLARE(CRAFT_TYPES_EXPORTED, uint32_t);
CRAFT_TYPE_DECLARE(CRAFT_TYPES_EXPORTED, uint64_t);

CRAFT_TYPE_DECLARE(CRAFT_TYPES_EXPORTED, int32_t);
CRAFT_TYPE_DECLARE(CRAFT_TYPES_EXPORTED, int64_t);

CRAFT_TYPE_DECLARE(CRAFT_TYPES_EXPORTED, float);
CRAFT_TYPE_DECLARE(CRAFT_TYPES_EXPORTED, double);
